### ISSUE TITLE
All LaravelShoppingcart don't work when using api call in laravel

### ISSUE THREAD

**Issue by leonfather** [Crinsane/LaravelShoppingcart#367]
Hello i have i problem and i can't resolve it All LaravelShoppingcart don't work when using api call in laravel to retrieve session data? Any idea?

**Comment by Crinsane** [comment]
I need more information to debug this. Are the API calls using a session or not? What is the code you use, which version of Laravel and this package. How can I reproduce this problem. Otherwise I can't help you.

**Comment by leonfather** [comment]
I'm using Redis driver with laravel 5.4

**Comment by leonfather** [comment]
Any idea please that can help me? it's like that a new session created or something like that, Can you help me?

**Comment by matejsvajger** [comment]
@leonfather Laravel routes in `routes/api.php` don't have a session by default. Either move your route to `routes/web.php` -> `Route::get('/api/test', "Frontoffice\CartController@test");` or enable sessions via middleware in API route group.

**Comment by leonfather** [comment]
@matejsvajger I still get the same problem

**Comment by Crinsane** [comment]
Does the normal laravel session work? Can you put something in the session and retreive it?

**Comment by leonfather** [comment]
yes it works i'm using redis in session I store my session data using 
`Redis::set('test', $value);`
And i retrieve this value 
`Redis::get('test', $value);`

**Comment by Crinsane** [comment]
That's not the Laravel session you're using. You're using Redis directly, and not via the session manager (which this package is using) Try with the Session facade please

https://laravel.com/docs/5.4/session

**Comment by leonfather** [comment]
i'm using session facade i only change SESSION_DRIVER=redis from file to redis

**Comment by leonfather** [comment]
But when i'm doing test to see if laravel session work or now i get those results : 
```
public function test(Request $request){
	$request->session()->put('key', 'value');
	$key = $request->session()->get('key');
	return response($key);
}
```
in the same route /test i get result : value
But when trying to access this value from an other route i get nothing. Any idea from where i get the problem ?

**Comment by matejsvajger** [comment]
@leonfather you're setting and retrieving the session value in the same call. Try retrieving it in a different function.

**Comment by leonfather** [comment]
yes i'm doing tests now and laravel session works fine, Any idea from where i get the problem ?

**Comment by leonfather** [comment]
in CartController in index method : 
```
public function index($prefix)
    {
		Cart::add(18, 'name one', 2, 44, array('size' => 'De4', 'stock' => '2'));
		if($prefix == translate('global.cart')){
			return view('frontoffice.cart.index');
		}
    }
```
With this code i get content in cart but if i comment Cart::add(18,...... i get nothing in cart content

**Comment by hakobfromlightin** [comment]
I have the same problem with cart, any help will be appreciated

**Comment by jakus1** [comment]
I had this problem just now and this is how I fixed it. First you need to change the api middleware group to:
```
'api' => [
	\App\Http\Middleware\EncryptCookies::class,
	\Illuminate\Session\Middleware\StartSession::class,
	\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse::class,
	\Illuminate\View\Middleware\ShareErrorsFromSession::class,
	'throttle:60,1',
	'bindings',
],
```
in 
```
app/Http/Kernel.php
```
It is important that all entries are there and that they are in this order.

**Comment by codeitlikemiley** [comment]
well 2 things you need to observe since im using this basically for vue SPA, and using api calls...
your api endpoints should be located in your routes/web.php
secondly, you need to make session lifetime, that way, even if the user abandon it, laravel will still recognize the session , so all data about the cart will be still there...
third , you need to use 
localstorage that will read the stored cart object , im using a modular store VUEX.
by default the localstorage check for the cart object if stored if not check my global state initial state
which also has the Cart Object.  Lastly if it cannot find the cart , then it just an empty array

**Comment by jsdecena** [comment]
The API is `session`-less since it is `token`-based. Surely, you will not be able to retrieve the items added in the current session since the token might not know who is the currently logged user ( unless you make the app known based on token and logged it in )

**Comment by OctaneInteractive** [comment]
Hi @codeitlikemiley, I'm creating a Vue SPA.

I've switched to the web routes, but `Cart::content()` still isn't giving me anything.

Are you using sessions?

**Comment by jordantsap** [comment]
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;
use App\Product;
use Gloudemans\Shoppingcart\Facades\Cart;
use Session;

**Comment by jamalali** [comment]
Is this still an isue for anyone else?

**Comment by stanhatk** [comment]
It's still an issue for me. When I add those middlewares to 'api' group, it brakes Passport auth:api system.

The workaround solution is to move shopping cart routes to web.php, wherein 'web' middleware session already exists and retrieves cart correctly.

**Comment by chrisvidal** [comment]
I found a solution by inserting the 'web' middleware in the api routes.php

```php
Route::group([
        'middleware' => ['web'],
        'prefix' => 'api',
        'namespace' => 'Api\Http\Controllers'
    ], function () {
```

hope that helps

**Comment by kratos619** [comment]
![api_add](https://user-images.githubusercontent.com/26537566/60665872-4bbb9600-9e83-11e9-9e7b-4fed100ee5d3.png)
this is add function to add item into cart
![api_function](https://user-images.githubusercontent.com/26537566/60665665-bddfab00-9e82-11e9-9284-6f9ad5d77f2b.png)
this is cart content function 
![api_route](https://user-images.githubusercontent.com/26537566/60665675-c33cf580-9e82-11e9-83c2-9b47917d569d.png)
this is route api to call that function

but in response i dont get any data in android device please helpppppppppppppppp

**Comment by mdkhaledhassan** [comment]
> 

same problem api get the cart empty but still cart item is shown in web. 
if you solve the problem then help me.
